MercadoGestor/MercadoGestor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from core.views import HomeTemplateView
from integration import views
admin.site.site_header = 'ManagerML'
urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('ml/', include(('core.urls', "core"))),
    path('accounts/', include(('users.urls', "users"))),
    path('subscribe/', include(('subscribe.urls', "subscribe"))),
    path('integration/', include(('integration.urls', 'integration'))),
    path('products/', include(('products.urls', 'products'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

MercadoGestor/core/urls.py
from django.urls import path

from core.views import (
    QuestionListView,
)

app_name = "core"
urlpatterns = [
    path("list/question", QuestionListView.as_view(), name="question_list"),

]

MercadoGestor/products/urls.py
from django.urls import path,re_path

from products import views

app_name = "products"
urlpatterns = [
    path('', views.ProductView, name='products'),
    path('<id>/<quantity>', views.ProductAvailableQuantity, name='product'),
    path('history', views.HistoryView, name='history'),
]

MercadoGestor/core/models/questons.py
from django.db import models


class QuestionCategory(models.Model):
    name = models.CharField("Categoria", max_length=200)

    class Meta:
        verbose_name = "Categoria da duvida"
        verbose_name_plural = "Categorias das duvidas"

    def __str__(self):
        return self.name


class Question(models.Model):
    question = models.CharField("Duvida", max_length=200)
    answer = models.TextField("Resposta")
    active = models.BooleanField(default=True)
    category = models.ForeignKey("core.QuestionCategory", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Duvidas Frequente"
        verbose_name_plural = "Duvidas Frequentes"

    def __str__(self):
        return self.question


class Address(models.Model):
    state = models.CharField("UF", max_length=30,blank=True)
    street = models.CharField("Rua", max_length=30,blank=True)
    city = models.CharField("Cidade", max_length=30,blank=True)
    zipcode = models.CharField("CEP", max_length=30,blank=True)
    country = models.CharField("Pais", max_length=30,blank=True)
    neighborhood = models.CharField("Bairro", max_length=30,blank=True)
    street_number = models.CharField("Numero", max_length=30,blank=True)
    complement = models.CharField(
        "Complemento", max_length=30, null=True, blank=True, default=""
    )

    class Meta:
        verbose_name = "Endereço da Loja"
        verbose_name_plural = "Endereços da Loja"

    def __str__(self):
        return f"{self.street}, {self.street_number} , {self.zipcode}"

    def get_short_address(self):
        return f"{self.street}, {self.street_number} ,{self.complement} ,{self.zipcode}"

    def get_full_address(self):
        return f"{self.street}, {self.street_number} ,{self.complement} ,{self.zipcode} {self.city}, {self.state} {self.contry}"

MercadoGestor/core/forms.py
import re
from os.path import splitext

from django import forms

from .models import (
    Address
)
from .utils import format_cnpj, valid_cnpj, validate_contact_phone, validate_email


class UploadForm(forms.Form):
    file = forms.ImageField()


class ContactFormSet(forms.BaseModelFormSet):
    def clean(self):
        super().clean()
        for form in self.forms:
            kind = form.cleaned_data.get("kind", "")
            contact = form.cleaned_data.get("contact", "")

            if kind is None:
                form.add_error("kind", "Tipo deve ser email ou telefone")

            if kind == "email":
                if contact is None:
                    form.add_error(
                        "contact", "Tipo e-mail não pode conter um e-mail vazio"
                    )
                else:
                    match = re.match("([^@|\s]+@[^@]+\.[^@|\s]+)", contact)
                    if not match:
                        form.add_error(
                            "contact",
                            "Tipo email deve conter uma e-mail valido em contato, email: %s não é valido"
                            % contact,
                        )


class AddressForm(forms.ModelForm):
    CHOICES = (
        ("0", "SELCIONE UM ESTADO"),
        ("AC", "AC"),
        ("AL", "AL"),
        ("AP", "AP"),
        ("AM", "AM"),
        ("BA", "BA"),
        ("CE", "CE"),
        ("DF", "DF"),
        ("ES", "ES"),
        ("GO", "GO"),
        ("MA", "MA"),
        ("MT", "MT"),
        ("MS", "MS"),
        ("MG", "MG"),
        ("PA", "PA"),
        ("PB", "PB"),
        ("PR", "PR"),
        ("PE", "PE"),
        ("PI", "PI"),
        ("RJ", "RJ"),
        ("RN", "RN"),
        ("RS", "RS"),
        ("RO", "RO"),
        ("RR", "RR"),
        ("SC", "SC"),
        ("SP", "SP"),
        ("SE", "SE"),
        ("TO", "TO"),
    )
    state = forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = Address
        fields = (
            "zipcode",
            "street",
            "street_number",
            "complement",
            "city",
            "neighborhood",
            "city",
            "state",
        )

    def clean_state(self):
        state = self.cleaned_data.get("state")
        if state == "0" or state is None:
            self.add_error("state", "Estado selecionado não é valido")
        return state

MercadoGestor/core/views.py
import logging
from datetime import datetime
from random import shuffle

from django.contrib import messages
from django.db.models import Q
from django.forms import modelformset_factory
from django.http import JsonResponse
from django.shortcuts import (
    get_list_or_404,
    get_object_or_404,
    redirect,
    render,
    resolve_url,
)
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)

# from .forms import EntityForm,AvatarForm
from .forms import AddressForm, ContactFormSet, UploadForm
from .models import (
    Address,
    Question,
    QuestionCategory,
)

# Create your views here.
logger = logging.getLogger(__name__)


class HomeTemplateView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, *args, **kwargs):
        contex = super().get_context_data(**kwargs)
        questions = list(Question.objects.filter(active=True))
        shuffle(questions)
        contex["questions"] = questions[:5]
        contex["background"] = [
            "background-1",
            "background-2",
            "background-3",
            "background-4",
        ]
        return contex


class QuestionListView(ListView):
    model = Question
    paginate_by = 5

    def get_queryset(self):
        question = self.request.GET.get("search", "")
        category_pk = self.request.GET.get("category", "0")
        category = QuestionCategory.objects.filter(pk=category_pk).first()

        if category_pk == "0":
            return self.model.objects.filter(question__icontains=question)

        return self.model.objects.filter(
            category=category, question__icontains=question
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = QuestionCategory.objects.all()
        return context


def termo_privacidade(request):
    return render(request, "termo.html", {})


def list_entity_and_project(request):
    term = request.GET.get("term")
    result = list(
        Entity.objects.filter(razao_social__icontains=term).values("razao_social", "id")
    )
    return JsonResponse(result, safe=False)

MercadoGestor/core/templates/base/base.html

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>
    {% block title %}
    ManagerML
    {% endblock %}
  </title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/favicon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Poppins:300,400,500,700" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link href="{% static 'lib/fontawesome/css/all.css' %}" rel="stylesheet">
  <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/owlcarousel/dist/assets/owl.carousel.min.css' %}" rel="stylesheet"> 
  <link href="{% static 'lib/owlcarousel/dist/assets/owl.theme.default.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

  <!-- Main Stylesheet File -->
    <link href="{% static 'css/style_buttons.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/style_header.css' %}" rel="stylesheet">
 <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
  

  <!-- =======================================================
    Theme Name: Regna
    Theme URL: https://bootstrapmade.com/regna-bootstrap-onepage-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->

  {% block custom_css %}
  {% endblock %}
</head>
{% block content %}
{% endblock %}

<body>


  <!-- Footer -->
  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <!-- JavaScript Libraries -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script
    src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
    integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
    crossorigin="anonymous">
  </script>
  
  <script src="{% static 'lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'lib/wow/wow.min.js' %}"></script>
  <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
  <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'lib/superfish/hoverIntent.js' %}"></script>
  <script src="{% static 'lib/superfish/superfish.min.js' %}"></script>
  <script src="{% static 'lib/popper/popper.min.js' %}"></script>
  <script src="{% static 'lib/multiselect/dist/js/BsMultiSelect.js' %}"></script>
  <script src="{% static 'js/select.js' %}"></script>
  <script src="{% static 'lib/owlcarousel/dist/owl.carousel.min.js' %}"></script>
  <!-- Contact Form JavaScript File -->
  <script src="{%  static 'contactform/contactform.js' %}"></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js' %}"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
  {% block custom_js %}
  {% endblock %}

</body>
</html>

MercadoGestor/core/templates/base/footer.html
 {% load static %}
 <!--==========================
    Footer
  ============================-->

  <!-- Footer -->
  <footer id="footer" class="page-footer font-small indigo">
    <!-- Copyright -->
    <div class="copyright footer-termos text-center text-dark py-3">
        <labe>
            <input type="checkbox" checked />
              Ao disponibilizar os seus dados através desta página, você concorda com o
         </labe>
        <a class="text-primary" href="#">Termo de Privacidade</a>
    </div>
    <!-- Copyright -->
      <div class="row footer-ps">
          <div class="col-md-8 text-center">
              <span class="text-muted ">
                  Todos os direitos reservados.© 2022 Copyright:
                  <strong> Amós Smart Solutions</strong></span>
          </div>
          <div class="col-md-4 text-center">
              <span class="text-muted"><strong>CNPJ:</strong> 36.637.086/0001-05</span>
          </div>
      </div>
  
  </footer>
  

MercadoGestor/core/templates/base/header_white.html
{% load static %}
<header id="header">
   <div  class="container header-one">
      <div class="">
         <div id="" class="pull-left pl-4 pl-md-3">
            <a class="pages decoration bold-text" href="{% url 'home' %}#main">
               <h2 class='bold-text'><b>
               {% if request.user.is_authenticated == False %}
                  ManagerML 
               {% else %} 
                  {{ request.user.company }}
               {% endif %}</b></h2>
            </a>
            <!-- Uncomment below if you prefer to use a text logo -->
            <!--<h1><a href="#hero">ManagerML</a></h1>-->
         </div>
         <nav id="nav-menu-container" >
            <ul class="nav-menu menu-center" >
               <li class="menu-active mr-5"><a class="pages decoration" id="parameter" href="{% url 'home' %}#main">Conheça a ML</a></li>
               <li class="mr-5"><a class="pages decoration" href="{% url 'home' %}#team">Ser Manager</a></li>
               <li class="mr-5"><a class="pages decoration" href="{% url 'home' %}#duvidas">Dúvidas</a></li>
            </ul>
            <ul class="nav-menu pull-right">
               {% if request.user.is_authenticated == False %}
               
               <li class="p-2 p-md-0">
                  <div class="btnEntrar">
                     <a href="{%  url 'users:login' %}" class="decoration font-weight-bold">
                        Entrar
                     </a>
                  </div>
               
                  {% else %}
                  <div class="">
                     <li class="menu-has-children dropdown">
                        <div class="btnEntrar">
                           <a href="#" class="decoration font-weight-bold w-100 h-100">Perfil</a>
                        </div>
                        <ul  style="border-radius: 10px;border-top-left-radius: 0px;">
                           
                           <a class="" href="{% url 'admin:index' %}"> 
                              <li class="p-2 border-bottom text-center">
                                 Administração 
                              </li>
                           </a>
                           <a class="" href="{% url 'products:products' %}"> 
                              <li class="p-2 border-bottom text-center">
                                 Meus Produtos
                              </li class="p-2">
                           </a>
                           
                           <a class="" href="{% url 'products:history' %}">
                              <li class="p-2 border-bottom text-center">
                                 Histórico ML
                              </li>
                           </a>
                          
                           <a class="" href="{%  url 'users:logout' %}">
                              <li class="p-2 text-center">
                                 Sair
                              </li>
                           </a>
                           
                        </ul>
                     </li>
                  </div>
                  {% endif %}
               </li>
            </ul>
         </nav><br><br>
         <!-- #nav-menu-container -->
      </div>
      <!-- col -->
   </div>
</header>
<!-- #header -->

MercadoGestor/core/templates/base/messages.html
<div class="conteiner">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    <p>
        {{ message|safe }}
    </p>
    </div>
    {% endfor %}
</div>

MercadoGestor/core/templates/base/pagination.html
<!-- pagination -->

<div class="row">
    <div class="" style="margin: auto; padding: 35px; margin-bottom: 50px;">
      <ul class="pagination" >
  
        {% if page_obj.has_previous %}
          <li class="page-item">
              <a 
                style="color:#9999ff; padding: 20px;"
                class="page-link"
                href="?page={{ page_obj.previous_page_number }}&search={{ request.GET.search }}">&laquo;</a>
            </li>
        {% else %}
          <li class="page-item disabled">
              <a 
              href="#" 
              style="color:#9999ff;padding: 20px;"
              class="page-link">&laquo;</a>
            </li>
        {% endif %}
  
        {% for pg in page_obj.paginator.page_range %}
  
            {% if page_obj.number == pg %}
                <li 
                    class="page-item active">
                  <a
                  style="color:#ffff; font-weight: 700; padding: 20px;"
                  class="page-link" 
                  href="#">{{ pg }}</a>
                </li>
            {% else %}
                  <a 
                    style="color:#808080;font-weight: 400;padding: 20px;"  class="page-link"
                    href="?page={{ pg }}&search={{ request.GET.search }}">
                    {{ pg }}
                  </a>
                </li>
            {% endif %}
  
        {% endfor %}
  
        {% if page_obj.has_next %}
          <li class="page-item">
              <a 
                style="color:#9999ff;padding: 20px;"
                class="page-link"
                href="?page={{ page_obj.next_page_number }}&search={{ request.GET.search }}">&raquo;</a>
            </li>
        {% else %}
          <li class="page-item disabled">
              <a
                style="color:#9999ff;padding: 20px;"
                class="page-link" 
                href="#"
                >&raquo;</a>
            </li>
        {% endif %}
      </ul>
    </div>
  </div>
  <!-- https://www.technovelty.org/web/skipping-pages-with-djangocorepaginator.html -->